#!/bin/bash
iptables -F



#############################################
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT

################################################# 
iptables -A INPUT -s 192.168.5.0/24 -p icmp -j ACCEPT
iptables -A OUTPUT -s 192.168.5.0/24 -p icmp -j ACCEPT
#####################################################
iptables -t filter -A INPUT -p udp --dport 53 -i enp0s3 -j ACCEPT
iptables -t filter -A FORWARD -p udp --dport 53 -i enp0s3 -j ACCEPT
############################################################
iptables -A INPUT -p tcp --dport 80 -i eth1 -j ACCEPT
iptables -A FORWARD -p tcp --dport 80 -i eth1 -j ACCEPT
iptables -A INPUT -p udp --dport 80 -i eth1 -j ACCEPT
iptables -A FORWARD -p udp --dport 80 -i eth1 -j ACCEPT
############################################################
iptables -A INPUT -p tcp --dport 21 -i eth1 -j ACCEPT
iptables -A FORWARD -p tcp --dport 21 -i eth1 -j ACCEPT
iptables -A INPUT -p udp --dport 21 -i eth1 -j ACCEPT
iptables -A FORWARD -p udp --dport 21 -i eth1 -j ACCEPT
##########################################################
iptables -A INPUT -p tcp --dport 25 -i eth1 -j ACCEPT
iptables -A FORWARD -p tcp --dport 25 -i eth1 -j ACCEPT
iptables -A INPUT -p udp --dport 25 -i eth1 -j ACCEPT
iptables -A FORWARD -p udp --dport 25 -i eth1 -j ACCEPT
#########################################################
iptables -A INPUT -p tcp --dport 443 -i eth1 -j ACCEPT
iptables -A FORWARD -p tcp --dport 443 -i eth1 -j ACCEPT
iptables -A INPUT -p udp --dport 443 -i eth1 -j ACCEPT
iptables -A FORWARD -p udp --dport 443 -i eth1 -j ACCEPT
#########################################################
iptables -A INPUT -p tcp --dport 587 -i eth1 -j ACCEPT
iptables -A FORWARD -p tcp --dport 587 -i eth1 -j ACCEPT
iptables -A INPUT -p udp --dport 587 -i eth1 -j ACCEPT
iptables -A FORWARD -p udp --dport 587 -i eth1 -j ACCEPT
		







iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP



